// <auto-generated />
namespace Session8_LibraryManagementUIMysqlEF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddBorrowHistories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBorrowHistories));
        
        string IMigrationMetadata.Id
        {
            get { return "202007140006268_AddBorrowHistories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
